-- Insert users

INSERT INTO T_USER (USER_ID, FIRST_NAME, LAST_NAME, USER_NAME, PASSWORD, EMAIL, STATUS)
VALUES (1, 'Sehan','Rathnayake','sehanhot','5qg1c2AzSqhfoeuN92QAgw==','sehan@gmail.com','ACT');


-- Insert Roles

INSERT INTO T_ROLE(ROLE_ID, ROLE_NAME)
VALUES(1,'USER');

INSERT INTO T_ROLE(ROLE_ID, ROLE_NAME)
VALUES(2,'ADMIN');

--Insert Privileges
INSERT INTO T_PRIVILEGE(PRIVILEGE_ID, DESCRIPTION)
VALUES(1,'Do a Test') ;

-- Assign privileges to roles
INSERT INTO T_ROLE_PRIVILEGE(ROLE_PRIVILEGE_ID, ROLE_ID, PRIVILEGE_ID)
VALUES(1,1,1);

INSERT INTO T_ROLE_PRIVILEGE(ROLE_PRIVILEGE_ID, ROLE_ID, PRIVILEGE_ID)
VALUES(2,2,1);


-- Assign Roles to Users

INSERT INTO T_USER_ROLE(USER_ROLE_ID, USER_ID, ROLE_ID)
VALUES (1,1,1);

