-- Insert users

INSERT INTO T_USER (USER_ID, FIRST_NAME, LAST_NAME, USER_NAME, PASSWORD, EMAIL, STATUS)
VALUES (1, 'Sehan','Rathnayake','sehanhot','5qg1c2AzSqhfoeuN92QAgw==','sehan@gmail.com','ACT');


-- Insert Roles

INSERT INTO T_ROLE(ROLE_ID, ROLE_NAME)
VALUES(1,'USER');

INSERT INTO T_ROLE(ROLE_ID, ROLE_NAME)
VALUES(2,'ADMIN');

--Insert Privileges
INSERT INTO T_PRIVILEGE(PRIVILEGE_ID, DESCRIPTION)
VALUES(1,'Do a Test') ;

-- Assign privileges to roles
INSERT INTO T_ROLE_PRIVILEGE(ROLE_PRIVILEGE_ID, ROLE_ID, PRIVILEGE_ID)
VALUES(1,1,1);

INSERT INTO T_ROLE_PRIVILEGE(ROLE_PRIVILEGE_ID, ROLE_ID, PRIVILEGE_ID)
VALUES(2,2,1);


-- Assign Roles to Users

INSERT INTO T_USER_ROLE(USER_ROLE_ID, USER_ID, ROLE_ID)
VALUES (1,1,1);


-- Insert customer

INSERT INTO T_CUSTOMER(CUSTOMER_ID, NAME, ADDRESS, EMAIL, PHONE)
VALUES (1, 'Heshani', 'Deshani, Kirinda', 'heshanisamarasekara@gmail.com', '0712189826');

-- Insert vehicle

INSERT INTO T_VEHICLE(VEHICLE_ID, VEHICLE_MODEL_ID, NUMBER_PLATE, MANUFACT_DATE, ODOMETER)
VALUES (1, 1, 'KE-9595', to_date('20100225','YYYYMMDD'), '25841');

-- Insert a vehicle model

INSERT INTO T_MODEL(VEHICLE_MODEL_ID, MANUFACTURER_ID, VEHICLE_TYPE, ENGINE_SIZE, FUEL_TYPE)
VALUES (1, 1, 'Car', '2.0', 'Petrol');

--Insert manufacturer

INSERT INTO T_MANUFACTURER(MANUFACTURER_ID, MANUFACT_NAME)
VALUES (1, 'BMW');