-- Sequences Related to Job

CREATE SEQUENCE Position_Seq
MINVALUE 1
START WITH 1
INCREMENT BY 50;

CREATE SEQUENCE Device_Seq
MINVALUE 1
START WITH 1
INCREMENT BY 50;

CREATE SEQUENCE Job_Seq
MINVALUE 1
START WITH 1
INCREMENT BY 50;

CREATE SEQUENCE Device_Mapping_Seq
MINVALUE 1
START WITH 1
INCREMENT BY 50;

CREATE SEQUENCE CustomerId_Seq
MINVALUE 1
START WITH 1
INCREMENT BY 50;
